### ISSUE TITLE
Unable to validate a valid hash

### ISSUE THREAD

**Issue by LucaVs** [hilch/Bcrypt.cpp#6]
Hi,
I have a bcrypt hash generated by another tool and I'm trying to validate it using this lib but it fails.

Here the hash: "$2y$10$F8zHvHjvjEvBEzdYewq48up1vy3bQSnmvguCr5X49CR90.QYq6iqi"
and here the plain pwd: "210319".

I can validate it using online tool: https://bcrypt-generator.com/

**Comment by hilch** [comment]
Hi,
thank you !
Looking into the current OpenBSD sources it seems they have improved their implementation in the meanwhile.
Unfortunately there is less time for me to use this newer code at the moment.
But I will tackle this.

**Comment by hilch** [comment]
see https://en.wikipedia.org/wiki/Bcrypt

"
$2x$, $2y$ (June 2011)

In June 2011, a bug was discovered in crypt_blowfish, a PHP implementation of bcrypt. It was mis-handling characters with the 8th bit set.[[13]](https://en.wikipedia.org/wiki/Bcrypt#cite_note-13) They suggested that system administrators update their existing password database, replacing $2a$ with $2x$, to indicate that those hashes are bad (and need to use the old broken algorithm). They also suggested the idea of having crypt_blowfish emit $2y$ for hashes generated by the fixed algorithm.

Nobody else, including canonical OpenBSD, adopted the idea of 2x/2y. This version marker change was limited to crypt_blowfish.
"

since we use code of OpenBSD there will be no change here.
